### ISSUE TITLE
[Feature]: Can we add the configuration for customize the percentage of abandoned colonies generated when world generates?

### ISSUE THREAD

**Issue by Ch3225** [gisellevonbingen-Minecraft/MineColonies_Tweaks#1]
### Cause for request

As title

### Request details

As title

**Comment by gisellevonbingen** [comment]
Added at 7c49e78f79226ab383bd0b05ddb046aad7f6c556
![image](https://github.com/gisellevonbingen-Minecraft/MineColonies_Tweaks/assets/44163945/41329dda-68f2-4712-b29f-bf6387d85adf)
