### ISSUE TITLE
MixinTransformerError: An unexpected critical error was encountered

### ISSUE THREAD

**Issue by evhub** [gisellevonbingen-Minecraft/MineColonies_Tweaks#13]
See crash report: https://gist.github.com/evhub/ae0034c27d3e71602889f3fb8bb711ed

This is on Minecraft 1.20.1, Forge 47.3.0, Minecolonies 1.1.610-BETA, and Minecolonies Tweaks 2.26.

**Comment by gisellevonbingen** [comment]
Please update Compatibility addon for MineColonies to latest version.
