### ISSUE TITLE
Minecolonies Crops Tweak

### ISSUE THREAD

**Issue by killkillsito** [gisellevonbingen-Minecraft/MineColonies_Tweaks#14]
You cant actually plant any minecolonies crop by yourself. Instead of that you must use the minecolonies farmer to plant the mod crops.
There is no university upgrade or setting in the mod to do that.
It would be great if that limitation gone, and we can plant any minecolonies crop to do automatic redstone farms for that crops.

**Comment by gisellevonbingen** [comment]
Done on 1.20.1-2.29 version.
You can change via config. 
https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-tweaks/files/5614588.
