### ISSUE TITLE
Crash with MineColonies 1.20.1-1-1.624-BETA

### ISSUE THREAD

**Issue by trav90** [gisellevonbingen-Minecraft/MineColonies_Tweaks#15]
Updated MineColonies this morning from 1.1.623 to 1.1.624 and Minecraft crashes on load. Reverting back to MineColonies 1.1.623-BETA works fine.

Minecraft Version: 1.20.1
NeoForge 47.1.106
MineColonies 1.1.624
MineColonies Tweaks 2.27
Crash log:
[crash-2024-08-05_06.54.34-fml.txt](https://github.com/user-attachments/files/16499744/crash-2024-08-05_06.54.34-fml.txt)

**Comment by gisellevonbingen** [comment]
Fixed, Thanks for report!
https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-tweaks/files/5601544

**Comment by trav90** [comment]
Thanks so much! Appreciate it!
