### ISSUE TITLE
Mod crashes on latest 1.20.1 Minecolonies update

### ISSUE THREAD

**Issue by ModernGamingWorld** [gisellevonbingen-Minecraft/MineColonies_Tweaks#17]
Mod ID: 'minecolonies', Requested by: 'minecolonies_tweaks', Expected range: '[1.20.1-1.1.629-BETA,)', Actual version: '1.1.636-1.20.1-beta'

**Comment by gisellevonbingen** [comment]
Fixed
https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-tweaks/files/5645664
