### ISSUE TITLE
[1.20.1] Crash on startpup on 2 latest versions of minecolonies (1.1.693, 1.1.694)

### ISSUE THREAD

**Issue by Tsyklop** [gisellevonbingen-Minecraft/MineColonies_Tweaks#21]
[crash-2024-10-23_09.41.10-fml.txt](https://github.com/user-attachments/files/17486374/crash-2024-10-23_09.41.10-fml.txt)

**Comment by gisellevonbingen** [comment]
Thanks for report.
Fixed at 1.20.1-2.37 version. [Download is here](https://www.curseforge.com/minecraft/mc-mods/minecolonies-tweaks/files/5836430).
