### ISSUE TITLE
How to add custom smelting recipes

### ISSUE THREAD

**Issue by Gunner76th** [gisellevonbingen-Minecraft/MineColonies_Tweaks#22]
I am working on a modpack where for the player ores have to be smelted via the blast furnace and not the normal furnace. This change is made via a KubeJS script which uses the  `event.remove({output:` method. The issue this causes is that the Smelter for Minecolonies is unable to do their job, since they cannot use the blast furnace. 

How would one go about creating a custom recipe to allow the Smelter to process ores in the furnace? And would it be possible to do this and maintain their chance to increase yield with fortune like it is normally? 

I am working on this for Minecraft 1.20.1, Minecolonies 1.1.627 Beta, and Tweaks addon for Minecolonies 2.29

**Comment by gisellevonbingen** [comment]
It hardcoded to use exactly vanilla Furnace  in MineColonies.
So it can't support to use blast furnace.

Maybe adding a new job be one solution, but not planned for now.
