### ISSUE TITLE
Possibility to turn the mourning off and on

### ISSUE THREAD

**Issue by KamilPacanek** [gisellevonbingen-Minecraft/MineColonies_Tweaks#6]
Hey can I somehow contribute to this mod with my change I was trying to PR into original MineColonies? See details here:
https://github.com/ldtteam/minecolonies-features/issues/840
https://github.com/ldtteam/minecolonies/pull/9974

Can you point me where I can start?

**Comment by gisellevonbingen** [comment]
1. Define 'mourningEnabled' to [MineColoniesTweaksConfigServer](https://github.com/gisellevonbingen-Minecraft/MineColonies_Tweaks/blob/1.19.2/src/main/java/steve_gall/minecolonies_tweaks/core/common/config/MineColoniesTweaksConfigServer.java)
2. Create Mixin class about '[CitizenMournHandler.java](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/entity/citizen/citizenhandlers/CitizenMournHandler.java)'
3. Write @Inject method about `public void addDeceasedCitizen(final String name)` at mixin class.

**Comment by KamilPacanek** [comment]
> 1. Define 'mourningEnabled' to [MineColoniesTweaksConfigServer](https://github.com/gisellevonbingen-Minecraft/MineColonies_Tweaks/blob/1.19.2/src/main/java/steve_gall/minecolonies_tweaks/core/common/config/MineColoniesTweaksConfigServer.java)
> 2. Create Mixin class about '[CitizenMournHandler.java](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/entity/citizen/citizenhandlers/CitizenMournHandler.java)'
> 3. Write @Inject method about `public void addDeceasedCitizen(final String name)` at mixin class.

Sounds great! I will see later today if I can make it work!

**Comment by gisellevonbingen** [comment]
How about don't show Mourn message too?
I think do it can be change Mixin target to  `void updateCitizenMourn(final ICitizenData data, final boolean mourn)` of [CitizenManager.java](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/colony/managers/CitizenManager.java).

**Comment by gisellevonbingen** [comment]
Have you any progress?

**Comment by KamilPacanek** [comment]
> Have you any progress?

No, haven't touched that after I've created that issue. Got carried away with other things (if you wish you can use my code).

**Comment by gisellevonbingen** [comment]
Yeah then I will gladly.

**Comment by gisellevonbingen** [comment]
Done with 1.19.2-1.22 and 1.20-12.22 version.

**Comment by KamilPacanek** [comment]
Ahh awesome! Gonna try it definitely next time I'll be playing with MC Colonies :)
